NOTE: A similar validation is performed in `test_model.ipynb`

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
from typing import Literal
import copy

from phd_visualizations.regression import regression_plot
from phd_visualizations.calculations import SupportedInstruments 
from phd_visualizations import save_figure

import combined_cooler
import matlab

%reload_ext autoreload
%autoreload 2

data_path = Path("../data")
model_type: Literal["physical", "data"] = "physical"

df = pd.read_csv(data_path / "cc_out_exp.csv")
df["Tcc_out"] = df["Tc_in"]
df

,Unnamed: 0,date,Tv,Tamb,HR,qc,Tc_in,Ce_cc,Ce,Tcond,...,mv,Tdc_out,Twct_out,wdc,wwct,qdc,qwct,Rp,Rs,Tcc_out
0,0,19-Feb-2025,36.261009,17.671711,43.180898,23.998493,28.121629,0.450381,3.653911,35.805044,...,224.076934,28.047818,27.778468,31.974352,22.470002,12.417720,12.259674,0.483,0.054,28.121629
1,1,10-Feb-2025,37.774713,13.531843,61.437262,24.000376,27.700450,0.432014,3.442630,37.052174,...,276.536959,27.430885,27.571514,30.637523,23.770823,12.005001,11.779023,0.500,0.000,27.700450
2,2,12-Feb-2025,36.241372,19.685473,23.739778,23.999315,28.145370,0.381511,4.625762,35.705996,...,217.364415,NaN,27.961559,0.000000,39.757368,0.235675,23.694971,0.990,0.000,28.145370
3,3,19-Feb-2025,37.575024,19.473600,38.711528,23.998248,27.738758,0.667380,4.861102,36.284572,...,263.510629,NaN,27.584572,0.000000,50.849622,0.390683,23.691506,0.984,0.201,27.738758
4,4,08-Jul-2025,37.389592,27.213752,50.149914,23.999880,28.115154,7.107880,10.170240,36.956869,...,258.600484,30.136470,24.924979,100.000000,66.439999,13.998713,9.773220,0.417,0.000,28.115154
5,5,08-Jul-2025,38.576245,28.395690,42.827841,24.001603,28.341443,7.863237,10.932670,38.064432,...,270.261573,31.153257,24.004598,100.000000,81.709604,14.000688,9.770016,0.417,0.000,28.341443
6,6,09-Jul-2025,42.399588,27.275200,62.124991,24.000049,35.196531,0.383408,4.809472,42.201587,...,200.822004,NaN,35.006526,0.000000,39.846699,0.119232,23.694192,0.995,0.000,35.196531
7,7,09-Jul-2025,39.453322,31.500935,41.542744,23.999335,28.792534,8.163791,11.842760,38.904821,...,280.806774,30.781717,27.996002,100.000000,86.901059,5.695932,18.024022,0.763,0.000,28.792534
8,8,13-Jan-2025,44.360271,12.164853,48.714282,24.002221,37.228958,0.271859,3.893380,43.848984,...,214.037281,36.973783,NaN,30.000000,0.000000,23.798313,0.000540,0.008,0.000,37.228958
9,9,02-Dec-2024,43.324459,20.923333,42.056077,17.998552,30.498067,1.947239,3.261430,42.871410,...,303.464304,30.478507,29.973642,59.506664,24.675237,11.778898,6.036892,0.346,0.000,30.498067
10,10,10-Jan-2025,43.082367,20.522458,22.689454,23.653935,35.036106,0.170597,5.017707,42.456457,...,219.734942,38.861176,34.883167,11.000000,22.418634,23.436685,23.336251,0.009,0.986,35.036106
11,11,02-Dec-2024,42.869820,20.486687,52.055926,17.999154,29.898601,0.595016,2.015121,42.321919,...,310.063340,29.182545,30.097002,34.701531,30.114162,6.650286,11.149655,0.631,0.000,29.898601
12,12,26-Jun-2025,42.500565,34.581011,14.231038,23.999826,34.924468,6.081220,9.669679,42.298175,...,211.182200,37.513516,32.148979,100.000000,30.000000,17.999185,12.001270,0.250,0.333,34.924468
13,13,06-Jun-2025,39.854605,30.700000,22.610000,23.496164,30.198575,4.247217,8.907215,39.477281,...,265.176334,34.121251,29.434439,78.736104,43.068955,23.250031,20.868657,0.010,0.887,30.198575
14,14,09-Jul-2025,42.399588,27.275200,62.124991,24.000049,35.196531,0.383408,4.809472,42.201587,...,200.822004,NaN,35.006526,0.000000,39.846699,0.119232,23.694192,0.995,0.000,35.196531
15,15,27-May-2025,45.425107,29.240422,17.713841,23.242701,36.217052,0.335793,5.182903,44.957641,...,245.835179,40.941588,36.052328,20.003386,28.648481,23.044723,22.908836,0.009,0.986,36.217052
16,16,12-Feb-2025,36.734509,15.593247,49.334973,24.000396,28.103939,0.463183,4.705314,36.223045,...,240.173450,NaN,27.919048,0.000000,43.357364,0.283769,23.695113,0.988,0.000,28.103939
17,17,17-Feb-2025,37.489978,20.218511,25.348266,23.485928,27.612022,0.485480,5.332590,36.954611,...,268.731485,32.312547,27.463384,21.000000,37.534535,23.281792,23.158949,0.009,0.986,27.612022
18,18,17-Feb-2025,37.489978,20.218511,25.348266,23.485928,27.612022,0.485480,5.332590,36.954611,...,268.731485,32.312547,27.463384,21.000000,37.534535,23.281792,23.158949,0.009,0.986,27.612022
19,19,19-Feb-2025,37.585918,21.026418,33.645355,24.002930,28.128553,0.544790,5.071566,37.093316,...,262.587107,31.283712,27.957560,25.000000,38.260553,15.294264,23.672190,0.363,0.978,28.128553
20,20,01-Jul-2025,54.648207,36.677142,14.316505,24.000688,44.328101,0.161654,4.727527,53.423163,...,239.540017,NaN,42.593710,11.003121,21.000000,23.789244,18.207007,0.009,0.756,44.328101
21,21,03-Jul-2025,56.608496,33.842684,31.552103,24.000054,48.105297,0.342105,3.646723,56.431734,...,274.686934,NaN,40.643478,26.442129,21.000000,18.000156,5.927470,0.250,0.000,48.105297
22,22,27-Jun-2025,54.674012,32.536467,21.397523,23.999274,45.564017,0.128667,4.527399,54.001999,...,229.925265,NaN,45.397477,0.000000,21.000565,0.000544,23.718957,1.000,0.000,45.564017
23,23,11-Jul-2025,54.362551,27.937277,31.445756,23.999951,44.114168,0.161603,3.791804,54.053380,...,298.851486,NaN,43.052616,11.000000,21.000000,6.000635,17.747227,0.750,0.000,44.114168

### Evaluate model

In [3]:
cc_model = combined_cooler.initialize()

print(f"Using MATLAB package: {cc_model.name}")

parameters_default = cc_model.default_parameters(nargout=1)

results_dfs = []
for model_type in ["data", "physical"]:
    params = copy.deepcopy(parameters_default)
    if model_type == "physical":
        
        params["dc_lb"] = matlab.double([[5.0600,   10.0, 5.2211, 11]])
        params["dc_ub"] = matlab.double([[50.7500,   50.0, 24.1543, 99.1800]])

        # WCT           "Tamb",     "HR",    "Tin",      "q",     "w_fan"
        params["wct_lb"] = matlab.double([[0.1,    0.1,     5.0,    5.0,       0.]])
        params["wct_ub"] = matlab.double([[50.0,   99.99,   55.0,   24.8400,  95.]])
    elif model_type == "data":    
        params["dc_model_data_path"] = "/workspaces/SOLhycool/modeling/matlab/component_models/dc_model_data.mat"
        params["wct_model_data_path"] = "/workspaces/SOLhycool/modeling/matlab/component_models/wct_model_data.mat"
    results: list[dict] = []
    for idx, ds in df.iterrows():

        qc_m3h = matlab.double([ds["qc"]])
        qdc_m3h = matlab.double([ds["qdc"]])
        qwct_m3h = matlab.double([ds["qwct"]])

        Rp, Rs = cc_model.flows_to_ratios(qc_m3h, qdc_m3h, qwct_m3h, nargout=2)

        Tamb_C = matlab.double([ds["Tamb"]])
        HR_pp = matlab.double([ds["HR"]])
        mv_kgh = matlab.double([ds["mv"]])
        wdc = matlab.double([ds["wdc"]])
        wwct = matlab.double([ds["wwct"]])
        Tv = matlab.double([ds["Tv"]])

        # Create the 'options' struct as a Python dictionary
        options = {
            'model_type': model_type,
            'parameters': params,  # Empty struct in MATLAB
            'lb': [], 'ub': [], 'x0': [], 'silence_warnings': True
        }

        Ce_kWe, Cw_lh, detailed = cc_model.combined_cooler_model(Tamb_C, HR_pp, mv_kgh, qc_m3h, Rp, Rs, wdc, wwct, Tv, options, nargout=3)
        
        
        results.append(detailed)
        
    results_dfs.append( pd.DataFrame(results) )

display(results_dfs[0])
display(results_dfs[1])

Authorization required, but no authorization protocol specified

Using MATLAB package: combined_cooler

,Tamb,HR,mv,qc,Rp,Rs,wdc,wwct,Ce,Cw,...,Tdc_in,Tdc_out,Ce_dc,Qdc,qwct,Twct_in,Twct_out,Ce_wct,Cw_wct,Qwct
0,17.671711,43.180898,224.076934,23.998493,0.483,0.054,31.974352,22.470002,5.096935,92.594846,...,33.159526,27.835118,0.312366,76.697196,12.261262,32.868585,27.490733,0.138014,92.594846,76.557338
1,13.531843,61.437262,276.536959,24.000376,0.500,0.000,30.637523,23.770823,5.079493,112.937130,...,33.821712,27.738266,0.284241,84.754647,12.000188,33.821712,26.948431,0.147773,112.937130,95.761066
2,19.685473,23.739778,217.364415,23.999315,0.990,0.000,0.000000,39.757368,5.028469,166.802855,...,33.278941,33.278941,0.000000,0.000000,23.759322,33.278941,28.959686,0.381511,166.802855,119.140562
3,19.473600,38.711528,263.510629,23.998248,0.984,0.201,0.000000,50.849622,5.313815,214.568197,...,33.888814,33.888814,0.000000,0.000000,23.691455,33.888814,28.832295,0.667380,214.568197,139.076575
4,27.213752,50.149914,258.600484,23.999880,0.417,0.000,100.000000,66.439999,11.755116,133.927631,...,33.771250,29.372727,5.867400,71.447959,10.007950,33.771250,23.766667,1.240480,133.927631,116.260286
5,28.395690,42.827841,270.261573,24.001603,0.417,0.000,100.000000,81.709604,12.511319,198.479095,...,34.989055,30.545062,5.867400,72.187182,10.008669,34.989055,24.098859,1.995837,198.479095,126.553453
6,27.275200,62.124991,200.822004,24.000049,0.995,0.000,0.000000,39.846699,5.030727,214.035596,...,40.385228,40.385228,0.000000,0.000000,23.880049,40.385228,34.774157,0.383408,214.035596,155.521376
7,31.500935,41.542744,280.806774,23.999335,0.763,0.000,100.000000,86.901059,12.810758,331.331028,...,35.843477,31.074363,5.867400,31.488302,18.311492,35.843477,28.501615,2.296391,331.331028,156.070547
8,12.164853,48.714282,214.037281,24.002221,0.008,0.000,30.000000,0.000000,4.920243,0.000000,...,42.299130,37.589103,0.271859,130.162140,0.192018,42.299130,42.299130,0.000000,0.000000,0.000000
9,20.923333,42.056077,303.464304,17.998552,0.346,0.000,59.506664,24.675237,4.204095,116.927160,...,39.959556,30.477610,1.791859,129.553037,6.227499,39.959556,29.040120,0.155379,116.927160,78.933167
10,20.522458,22.689454,219.734942,23.653935,0.009,0.986,11.000000,22.418634,4.649999,135.689297,...,40.880347,38.597642,0.032940,62.104835,23.325761,38.618475,34.817397,0.137658,135.689297,102.910439
11,20.486687,52.055926,310.063340,17.999154,0.631,0.000,34.701531,30.114162,2.852061,171.970314,...,39.330318,30.050909,0.379688,71.538761,11.357466,39.330318,29.188148,0.215329,171.970314,133.709404
12,34.581011,14.231038,211.182200,23.999826,0.250,0.333,100.000000,30.000000,10.728429,166.732065,...,40.367183,36.589457,5.867400,78.922925,11.993913,38.479265,30.790376,0.213820,166.732065,107.045401
13,30.700000,22.610000,265.176334,23.496164,0.010,0.887,78.736104,43.068955,8.651361,179.582721,...,36.634490,33.697943,3.790971,79.287477,20.867648,33.731008,28.950253,0.456246,179.582721,115.819330
14,27.275200,62.124991,200.822004,24.000049,0.995,0.000,0.000000,39.846699,5.030727,214.035596,...,40.385228,40.385228,0.000000,0.000000,23.880049,40.385228,34.774157,0.383408,214.035596,155.521376
15,29.240422,17.713841,245.835179,23.242701,0.009,0.986,20.003386,28.648481,4.620706,210.316455,...,43.049942,41.559598,0.139018,39.842615,22.920232,41.573200,35.925370,0.196775,210.316455,150.245872
16,15.593247,49.334973,240.173450,24.000396,0.988,0.000,0.000000,43.357364,5.110671,180.187834,...,33.381193,33.381193,0.000000,0.000000,23.712391,33.381193,28.815278,0.463183,180.187834,125.695729
17,20.218511,25.348266,268.731485,23.485928,0.009,0.986,21.000000,37.534535,4.884769,121.246382,...,33.661988,30.863438,0.149068,75.614173,23.160084,30.888980,27.708649,0.336412,121.246382,85.522840
18,20.218511,25.348266,268.731485,23.485928,0.009,0.986,21.000000,37.534535,4.884769,121.246382,...,33.661988,30.863438,0.149068,75.614173,23.160084,30.888980,27.708649,0.336412,121.246382,85.522840
19,21.026418,33.645355,262.587107,24.002930,0.363,0.978,25.000000,38.260553,5.193523,132.304092,...,33.924640,30.500803,0.194095,60.772462,23.666553,31.761321,28.473980,0.350695,132.304092,90.328407
20,36.677142,14.316505,239.540017,24.000688,0.009,0.756,0.000000,0.000000,4.647632,0.000000,...,52.517400,52.517400,0.000000,0.000000,18.197226,52.517400,52.517400,0.000000,0.000000,0.000000
21,33.842684,31.552103,274.686934,24.000054,0.250,0.000,0.000000,0.000000,4.647321,0.000000,...,54.153150,54.153150,0.000000,0.000000,6.000014,54.153150,54.153150,0.000000,0.000000,0.000000
22,32.536467,21.397523,229.925265,23.999274,1.000,0.000,0.000000,0.000000,4.646938,0.000000,...,52.623592,52.623592,0.000000,0.000000,23.999274,52.623592,52.623592,0.000000,0.000000,0.000000
23,27.937277,31.445756,298.851486,23.999951,0.750,0.000,0.000000,0.000000,4.647270,0.000000,...,51.725479,51.725479,0.000000,0.000000,17.999963,51.725479,51.725479,0.000000,0.000000,0.000000

,Tamb,HR,mv,qc,Rp,Rs,wdc,wwct,Ce,Cw,...,Tdc_in,Tdc_out,Ce_dc,Qdc,qwct,Twct_in,Twct_out,Ce_wct,Cw_wct,Qwct
0,17.671711,43.180898,224.076934,23.998493,0.483,0.054,31.974352,22.470002,5.096935,95.530043,...,33.159526,28.069098,0.312366,73.326200,12.261262,32.881371,27.294913,0.138014,95.530043,79.527473
1,13.531843,61.437262,276.536959,24.000376,0.500,0.000,30.637523,23.770823,5.079493,111.887307,...,33.821712,27.215875,0.284241,92.034140,12.000188,33.821712,26.969546,0.147773,111.887307,95.466819
2,19.685473,23.739778,217.364415,23.999315,0.990,0.000,0.000000,39.757368,5.028469,195.773397,...,33.278941,33.278941,0.000000,0.000000,23.759322,33.278941,27.600132,0.381511,195.773397,156.648623
3,19.473600,38.711528,263.510629,23.998248,0.984,0.201,0.000000,50.849622,5.313815,225.389836,...,33.888814,33.888814,0.000000,0.000000,23.691455,33.888814,27.224474,0.667380,225.389836,183.307771
4,27.213752,50.149914,258.600484,23.999880,0.417,0.000,100.000000,66.439999,11.755116,149.206450,...,33.771250,29.688823,5.867400,66.312809,10.007950,33.771250,24.469662,1.240480,149.206450,108.088079
5,28.395690,42.827841,270.261573,24.001603,0.417,0.000,100.000000,81.709604,12.511319,182.263510,...,34.989055,30.877860,5.867400,66.780750,10.008669,34.989055,23.918692,1.995837,182.263510,128.647991
6,27.275200,62.124991,200.822004,24.000049,0.995,0.000,0.000000,39.846699,5.030727,219.390853,...,40.385228,40.385228,0.000000,0.000000,23.880049,40.385228,34.241805,0.383408,219.390853,170.277363
7,31.500935,41.542744,280.806774,23.999335,0.763,0.000,100.000000,86.901059,12.810758,241.868112,...,35.843477,32.158253,5.867400,24.331311,18.311492,35.843477,27.914413,2.296391,241.868112,168.555730
8,12.164853,48.714282,214.037281,24.002221,0.008,0.000,30.000000,0.000000,4.920243,0.000000,...,42.299130,36.823954,0.271859,151.307410,0.192018,42.299130,42.299130,0.000000,0.000000,0.000000
9,20.923333,42.056077,303.464304,17.998552,0.346,0.000,59.506664,24.675237,4.204095,119.041564,...,39.959556,29.958103,1.791859,136.652312,6.227499,39.959556,26.671981,0.155379,119.041564,96.056359
10,20.522458,22.689454,219.734942,23.653935,0.009,0.986,11.000000,22.418634,4.649999,172.452845,...,40.880347,39.643558,0.032940,33.648855,23.325761,39.654846,34.730340,0.137658,172.452845,133.324779
11,20.486687,52.055926,310.063340,17.999154,0.631,0.000,34.701531,30.114162,2.852061,163.996972,...,39.330318,29.255232,0.379688,77.674108,11.357466,39.330318,29.323330,0.215329,163.996972,131.926892
12,34.581011,14.231038,211.182200,23.999826,0.250,0.333,100.000000,30.000000,10.728429,165.043572,...,40.367183,37.174618,5.867400,66.697727,11.993913,38.771699,30.578581,0.213820,165.043572,114.065159
13,30.700000,22.610000,265.176334,23.496164,0.010,0.887,78.736104,43.068955,8.651361,189.211232,...,36.634490,34.234251,3.790971,64.806478,20.867648,34.261277,28.801894,0.456246,189.211232,132.258417
14,27.275200,62.124991,200.822004,24.000049,0.995,0.000,0.000000,39.846699,5.030727,219.390853,...,40.385228,40.385228,0.000000,0.000000,23.880049,40.385228,34.241805,0.383408,219.390853,170.277363
15,29.240422,17.713841,245.835179,23.242701,0.009,0.986,20.003386,28.648481,4.620706,218.139654,...,43.049942,41.316385,0.139018,46.344595,22.920232,41.332206,35.258294,0.196775,218.139654,161.581569
16,15.593247,49.334973,240.173450,24.000396,0.988,0.000,0.000000,43.357364,5.110671,202.131435,...,33.381193,33.381193,0.000000,0.000000,23.712391,33.381193,27.206526,0.463183,202.131435,169.991933
17,20.218511,25.348266,268.731485,23.485928,0.009,0.986,21.000000,37.534535,4.884769,168.772485,...,33.661988,31.916901,0.149068,47.149361,23.160084,31.932828,26.953097,0.336412,168.772485,133.909431
18,20.218511,25.348266,268.731485,23.485928,0.009,0.986,21.000000,37.534535,4.884769,168.772485,...,33.661988,31.916901,0.149068,47.149361,23.160084,31.932828,26.953097,0.336412,168.772485,133.909431
19,21.026418,33.645355,262.587107,24.002930,0.363,0.978,25.000000,38.260553,5.193523,163.713275,...,33.924640,31.027850,0.194095,51.416770,23.666553,32.094331,27.375699,0.350695,163.713275,129.660349
20,36.677142,14.316505,239.540017,24.000688,0.009,0.756,0.000000,21.000000,4.776296,262.206748,...,52.517400,52.517400,0.000000,0.000000,18.197226,52.517400,43.602939,0.128664,262.206748,188.306421
21,33.842684,31.552103,274.686934,24.000054,0.250,0.000,0.000000,21.000000,4.775985,179.141346,...,54.153150,54.153150,0.000000,0.000000,6.000014,54.153150,35.160466,0.128664,179.141346,132.268486
22,32.536467,21.397523,229.925265,23.999274,1.000,0.000,0.000000,21.000565,4.775605,282.158612,...,52.623592,52.623592,0.000000,0.000000,23.999274,52.623592,45.220979,0.128667,282.158612,206.235891
23,27.937277,31.445756,298.851486,23.999951,0.750,0.000,0.000000,21.000000,4.775934,264.993471,...,51.725479,51.725479,0.000000,0.000000,17.999963,51.725479,42.446142,0.128664,264.993471,193.881885

In [12]:
# Export resutlts
for model_type, results_df in zip(["data", "physical"], results_dfs):
    
    results_df.loc[results_df["Qdc"] < 1, "Tdc_out"] = np.nan
    results_df.loc[results_df["Qwct"] < 1, "Twct_out"] = np.nan
    
    results_df.to_csv(data_path / f"cc_out_mod_{model_type}.csv", index=False)
    print(f"Exported {data_path / f'cc_out_mod_{model_type}.csv'}")

df.loc[results_dfs[-1]["Qdc"] < 1, "Tdc_out"] = np.nan    
df.loc[results_dfs[-1]["Qwct"] < 1, "Twct_out"] = np.nan

df.to_csv(data_path / "cc_out_exp.csv")

Exported ../data/cc_out_mod_data.csv
Exported ../data/cc_out_mod_physical.csv

### Take from pre-evaluated

In [2]:
df = pd.read_csv(data_path / "cc_out_exp.csv", index_col=0)
results_df = pd.read_csv(data_path / "cc_out_mod_physical.csv")

df["Qdc"] = results_df["Qdc"]
df["Qwct"] = results_df["Qwct"]
df["Qc"] = results_df["Qc_released"]

display(df)
display(results_df)

,date,Tv,Tamb,HR,qc,Tc_in,Ce_cc,Ce,Tcond,Tdc_in,...,wdc,wwct,qdc,qwct,Rp,Rs,Tcc_out,Qdc,Qwct,Qc
0,19-Feb-2025,36.261009,17.671711,43.180898,23.998493,28.121629,0.450381,3.653911,35.805044,33.494083,...,31.974352,22.470002,12.417720,12.259674,0.483,0.054,28.121629,73.326200,79.527473,150.314103
1,10-Feb-2025,37.774713,13.531843,61.437262,24.000376,27.700450,0.432014,3.442630,37.052174,34.112194,...,30.637523,23.770823,12.005001,11.779023,0.500,0.000,27.700450,92.034140,95.466819,185.227531
2,12-Feb-2025,36.241372,19.685473,23.739778,23.999315,28.145370,0.381511,4.625762,35.705996,21.977082,...,0.000000,39.757368,0.235675,23.694971,0.990,0.000,28.145370,0.000000,156.648623,145.814074
3,19-Feb-2025,37.575024,19.473600,38.711528,23.998248,27.738758,0.667380,4.861102,36.284572,31.971167,...,0.000000,50.849622,0.390683,23.691506,0.984,0.201,27.738758,0.000000,183.307771,176.537254
4,08-Jul-2025,37.389592,27.213752,50.149914,23.999880,28.115154,7.107880,10.170240,36.956869,34.384180,...,100.000000,66.439999,13.998713,9.773220,0.417,0.000,28.115154,66.312809,108.088079,173.279537
5,08-Jul-2025,38.576245,28.395690,42.827841,24.001603,28.341443,7.863237,10.932670,38.064432,35.242784,...,100.000000,81.709604,14.000688,9.770016,0.417,0.000,28.341443,66.780750,128.647991,180.880465
6,09-Jul-2025,42.399588,27.275200,62.124991,24.000049,35.196531,0.383408,4.809472,42.201587,25.526867,...,0.000000,39.846699,0.119232,23.694192,0.995,0.000,35.196531,0.000000,170.277363,133.895591
7,09-Jul-2025,39.453322,31.500935,41.542744,23.999335,28.792534,8.163791,11.842760,38.904821,35.742446,...,100.000000,86.901059,5.695932,18.024022,0.763,0.000,28.792534,24.331311,168.555730,187.774619
8,13-Jan-2025,44.360271,12.164853,48.714282,24.002221,37.228958,0.271859,3.893380,43.848984,42.061851,...,30.000000,0.000000,23.798313,0.000540,0.008,0.000,37.228958,151.307410,0.000000,142.427062
9,02-Dec-2024,43.324459,20.923333,42.056077,17.998552,30.498067,1.947239,3.261430,42.871410,40.086938,...,59.506664,24.675237,11.778898,6.036892,0.346,0.000,30.498067,136.652312,96.056359,202.144133
10,10-Jan-2025,43.082367,20.522458,22.689454,23.653935,35.036106,0.170597,5.017707,42.456457,40.196202,...,11.000000,22.418634,23.436685,23.336251,0.009,0.986,35.036106,33.648855,133.324779,146.405638
11,02-Dec-2024,42.869820,20.486687,52.055926,17.999154,29.898601,0.595016,2.015121,42.321919,39.623784,...,34.701531,30.114162,6.650286,11.149655,0.631,0.000,29.898601,77.674108,131.926892,206.633807
12,26-Jun-2025,42.500565,34.581011,14.231038,23.999826,34.924468,6.081220,9.669679,42.298175,40.187571,...,100.000000,30.000000,17.999185,12.001270,0.250,0.333,34.924468,66.697727,114.065159,140.788925
13,06-Jun-2025,39.854605,30.700000,22.610000,23.496164,30.198575,4.247217,8.907215,39.477281,36.854286,...,78.736104,43.068955,23.250031,20.868657,0.010,0.887,30.198575,64.806478,132.258417,177.251902
14,09-Jul-2025,42.399588,27.275200,62.124991,24.000049,35.196531,0.383408,4.809472,42.201587,25.526867,...,0.000000,39.846699,0.119232,23.694192,0.995,0.000,35.196531,0.000000,170.277363,133.895591
15,27-May-2025,45.425107,29.240422,17.713841,23.242701,36.217052,0.335793,5.182903,44.957641,42.762154,...,20.003386,28.648481,23.044723,22.908836,0.009,0.986,36.217052,46.344595,161.581569,163.411695
16,12-Feb-2025,36.734509,15.593247,49.334973,24.000396,28.103939,0.463183,4.705314,36.223045,16.941505,...,0.000000,43.357364,0.283769,23.695113,0.988,0.000,28.103939,0.000000,169.991933,161.036513
17,17-Feb-2025,37.489978,20.218511,25.348266,23.485928,27.612022,0.485480,5.332590,36.954611,34.259260,...,21.000000,37.534535,23.281792,23.158949,0.009,0.986,27.612022,47.149361,133.909431,180.050091
18,17-Feb-2025,37.489978,20.218511,25.348266,23.485928,27.612022,0.485480,5.332590,36.954611,34.259260,...,21.000000,37.534535,23.281792,23.158949,0.009,0.986,27.612022,47.149361,133.909431,180.050091
19,19-Feb-2025,37.585918,21.026418,33.645355,24.002930,28.128553,0.544790,5.071566,37.093316,34.427904,...,25.000000,38.260553,15.294264,23.672190,0.363,0.978,28.128553,51.416770,129.660349,175.916649
20,01-Jul-2025,54.648207,36.677142,14.316505,24.000688,44.328101,0.161654,4.727527,53.423163,50.083774,...,11.003121,21.000000,23.789244,18.207007,0.009,0.756,44.328101,0.000000,188.306421,157.745271
21,03-Jul-2025,56.608496,33.842684,31.552103,24.000054,48.105297,0.342105,3.646723,56.431734,54.263118,...,26.442129,21.000000,18.000156,5.927470,0.250,0.000,48.105297,0.000000,132.268486,180.527272
22,27-Jun-2025,54.674012,32.536467,21.397523,23.999274,45.564017,0.128667,4.527399,54.001999,42.955688,...,0.000000,21.000565,0.000544,23.718957,1.000,0.000,45.564017,0.000000,206.235891,151.409629
23,11-Jul-2025,54.362551,27.937277,31.445756,23.999951,44.114168,0.161603,3.791804,54.053380,51.311346,...,11.000000,21.000000,6.000635,17.747227,0.750,0.000,44.114168,0.000000,193.881885,196.861440

,Tamb,HR,mv,qc,Rp,Rs,wdc,wwct,Ce,Cw,...,Tdc_in,Tdc_out,Ce_dc,Qdc,qwct,Twct_in,Twct_out,Ce_wct,Cw_wct,Qwct
0,17.671711,43.180898,224.076934,23.998493,0.483,0.054,31.974352,22.470002,5.096935,95.530043,...,33.159526,28.069098,0.312366,73.326200,12.261262,32.881371,27.294913,0.138014,95.530043,79.527473
1,13.531843,61.437262,276.536959,24.000376,0.500,0.000,30.637523,23.770823,5.079493,111.887307,...,33.821712,27.215875,0.284241,92.034140,12.000188,33.821712,26.969546,0.147773,111.887307,95.466819
2,19.685473,23.739778,217.364415,23.999315,0.990,0.000,0.000000,39.757368,5.028469,195.773397,...,33.278941,NaN,0.000000,0.000000,23.759322,33.278941,27.600132,0.381511,195.773397,156.648623
3,19.473600,38.711528,263.510629,23.998248,0.984,0.201,0.000000,50.849622,5.313815,225.389836,...,33.888814,NaN,0.000000,0.000000,23.691455,33.888814,27.224474,0.667380,225.389836,183.307771
4,27.213752,50.149914,258.600484,23.999880,0.417,0.000,100.000000,66.439999,11.755116,149.206450,...,33.771250,29.688823,5.867400,66.312809,10.007950,33.771250,24.469662,1.240480,149.206450,108.088079
5,28.395690,42.827841,270.261573,24.001603,0.417,0.000,100.000000,81.709604,12.511319,182.263510,...,34.989055,30.877860,5.867400,66.780750,10.008669,34.989055,23.918692,1.995837,182.263510,128.647991
6,27.275200,62.124991,200.822004,24.000049,0.995,0.000,0.000000,39.846699,5.030727,219.390853,...,40.385228,NaN,0.000000,0.000000,23.880049,40.385228,34.241805,0.383408,219.390853,170.277363
7,31.500935,41.542744,280.806774,23.999335,0.763,0.000,100.000000,86.901059,12.810758,241.868112,...,35.843477,32.158253,5.867400,24.331311,18.311492,35.843477,27.914413,2.296391,241.868112,168.555730
8,12.164853,48.714282,214.037281,24.002221,0.008,0.000,30.000000,0.000000,4.920243,0.000000,...,42.299130,36.823954,0.271859,151.307410,0.192018,42.299130,NaN,0.000000,0.000000,0.000000
9,20.923333,42.056077,303.464304,17.998552,0.346,0.000,59.506664,24.675237,4.204095,119.041564,...,39.959556,29.958103,1.791859,136.652312,6.227499,39.959556,26.671981,0.155379,119.041564,96.056359
10,20.522458,22.689454,219.734942,23.653935,0.009,0.986,11.000000,22.418634,4.649999,172.452845,...,40.880347,39.643558,0.032940,33.648855,23.325761,39.654846,34.730340,0.137658,172.452845,133.324779
11,20.486687,52.055926,310.063340,17.999154,0.631,0.000,34.701531,30.114162,2.852061,163.996972,...,39.330318,29.255232,0.379688,77.674108,11.357466,39.330318,29.323330,0.215329,163.996972,131.926892
12,34.581011,14.231038,211.182200,23.999826,0.250,0.333,100.000000,30.000000,10.728429,165.043572,...,40.367183,37.174618,5.867400,66.697727,11.993913,38.771699,30.578581,0.213820,165.043572,114.065159
13,30.700000,22.610000,265.176334,23.496164,0.010,0.887,78.736104,43.068955,8.651361,189.211232,...,36.634490,34.234251,3.790971,64.806478,20.867648,34.261277,28.801894,0.456246,189.211232,132.258417
14,27.275200,62.124991,200.822004,24.000049,0.995,0.000,0.000000,39.846699,5.030727,219.390853,...,40.385228,NaN,0.000000,0.000000,23.880049,40.385228,34.241805,0.383408,219.390853,170.277363
15,29.240422,17.713841,245.835179,23.242701,0.009,0.986,20.003386,28.648481,4.620706,218.139654,...,43.049942,41.316385,0.139018,46.344595,22.920232,41.332206,35.258294,0.196775,218.139654,161.581569
16,15.593247,49.334973,240.173450,24.000396,0.988,0.000,0.000000,43.357364,5.110671,202.131435,...,33.381193,NaN,0.000000,0.000000,23.712391,33.381193,27.206526,0.463183,202.131435,169.991933
17,20.218511,25.348266,268.731485,23.485928,0.009,0.986,21.000000,37.534535,4.884769,168.772485,...,33.661988,31.916901,0.149068,47.149361,23.160084,31.932828,26.953097,0.336412,168.772485,133.909431
18,20.218511,25.348266,268.731485,23.485928,0.009,0.986,21.000000,37.534535,4.884769,168.772485,...,33.661988,31.916901,0.149068,47.149361,23.160084,31.932828,26.953097,0.336412,168.772485,133.909431
19,21.026418,33.645355,262.587107,24.002930,0.363,0.978,25.000000,38.260553,5.193523,163.713275,...,33.924640,31.027850,0.194095,51.416770,23.666553,32.094331,27.375699,0.350695,163.713275,129.660349
20,36.677142,14.316505,239.540017,24.000688,0.009,0.756,0.000000,21.000000,4.776296,262.206748,...,52.517400,NaN,0.000000,0.000000,18.197226,52.517400,43.602939,0.128664,262.206748,188.306421
21,33.842684,31.552103,274.686934,24.000054,0.250,0.000,0.000000,21.000000,4.775985,179.141346,...,54.153150,NaN,0.000000,0.000000,6.000014,54.153150,35.160466,0.128664,179.141346,132.268486
22,32.536467,21.397523,229.925265,23.999274,1.000,0.000,0.000000,21.000565,4.775605,282.158612,...,52.623592,NaN,0.000000,0.000000,23.999274,52.623592,45.220979,0.128667,282.158612,206.235891
23,27.937277,31.445756,298.851486,23.999951,0.750,0.000,0.000000,21.000000,4.775934,264.993471,...,51.725479,NaN,0.000000,0.000000,17.999963,51.725479,42.446142,0.128664,264.993471,193.881885

In [21]:
from phd_visualizations.super_makers import SuperMarker

fig = regression_plot(
    df_ref= df, 
    df_mod= results_df, 
    alternative_labels="Physical", # "Data", 
    var_ids=["Tdc_out", "Twct_out", "Tc_in", "Tc_out", "Cw"], 
    units=["℃"]*4 + ["l/h"], 
    instruments=[SupportedInstruments.pt100]*4 + [SupportedInstruments.paddle_wheel_flow_meter],
    show_error_metrics=["r2", "mae"],
    var_labels=[
        '<span style="color:#83b366; font-weight:bold;">DC</span> outlet temperature', 
        '<span style="color:#9573a6; font-weight:bold;">WCT</span> outlet temperature', 
        "Condenser inlet temp.", 
        "Condenser outlet temp.", 
        "Water consumption"
    ],
    legend_pos="top_spaced",
    inline_error_metrics_text=True,
    
    # kwargs for layout
    # title_text='<span style="color:#83b366; font-weight:bold;">Combined</span> <span style="color:#9573a6; font-weight:bold;">cooling</span> model validation',
    title_text='<span style="font-weight:bold;">Combined</span> <span style="font-weight:bold;">cooler</span> model validation',
    title_font_size=21,
    legend_y = 1.015,
    title_y=0.995,
    # legend_font=dict(size=12),
    width=480,
    height=1900,
    vertical_spacing=0.05,
    margin=dict(l=10, r=30, t=120, b=10),
    font_size=10,
    
    super_marker=SuperMarker(
        size_var_id="Qc",
        size_var_range=[df["Qc"].min(), df["Qc"].max()],
        size_label="Cooling power",
        
        fill_var_id="Tamb",
        fill_label="Ambient temperature",
        fill_var_range=[10, 35],
        
        ring_vars_ids=["Qdc", "Qwct"],
        ring_labels=("Q̇<sub>dc</sub>", "Q̇<sub>wct</sub>")
    )
)

fig

In [22]:
save_figure(
    fig,
    figure_name="cc_model_regression",
    figure_path=Path("../results"),
    formats=["png", "svg"],
    scale=1
)

2025-07-24 18:33:52.149 | INFO     | phd_visualizations:save_figure:41 - Figure saved in ../results/cc_model_regression.png
2025-07-24 18:33:52.688 | INFO     | phd_visualizations:save_figure:41 - Figure saved in ../results/cc_model_regression.svg