In [22]:
from pathlib import Path
import hjson
import pandas as pd
from loguru import logger

from phd_visualizations.test_timeseries import experimental_results_plot
from phd_visualizations import save_figure
from solhycool_visualization.analysis import year_pie_plot

# auto reload modules
%load_ext autoreload
%autoreload 2

data_path: Path = Path("../../data")
results_path: Path = Path("/workspaces/SOLhycool/simulation/results/")

# 20220201_20220228/cc_static/df_sim_eval_at_20250401T0814_andasol.h5
file_path: Path = results_path / "20220101_20221231/cc_static/df_sim_eval_at_20250331T1959_andasol.h5"


df = pd.read_hdf(file_path)
for var_id in ["Tv", "Tc_in", "Tc_out"]: # TODO: This should be provided directly by OperationPoint.null
    df.loc[df[var_id] < 5, var_id] = None
df

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,Tamb,HR,mv,Tv,qc,Tc_in,Tc_out,Tcond,Qc_released,Qc_absorbed,...,Vavail_s1,Je,Jw,J,Je_c,Je_dc,Je_wct,Jw_wct,Jw_s1,Jw_s2
2022-01-01 00:00:00+00:00,0.00,0.0,0.00000,NaN,0.000000,NaN,NaN,0.00,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-01 01:00:00+00:00,0.00,0.0,0.00000,NaN,0.000000,NaN,NaN,0.00,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-01 02:00:00+00:00,0.00,0.0,0.00000,NaN,0.000000,NaN,NaN,0.00,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-01 03:00:00+00:00,0.00,0.0,0.00000,NaN,0.000000,NaN,NaN,0.00,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-01 04:00:00+00:00,0.00,0.0,0.00000,NaN,0.000000,NaN,NaN,0.00,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31 19:00:00+00:00,9.06,71.0,174.29552,31.55,22.896953,25.131056,29.418944,31.55,117.463256,114.015283,...,0.885024,0.033644,0.003310,0.036954,0.031354,0.000559,0.001731,0.003310,0.003310,0.0
2022-12-31 20:00:00+00:00,9.06,76.0,194.73712,33.14,18.392218,25.002628,31.137372,33.14,131.034840,131.021458,...,0.885024,0.010471,0.001439,0.011910,0.008788,0.001195,0.000489,0.001439,0.001439,0.0
2022-12-31 21:00:00+00:00,9.06,79.0,240.53908,36.66,16.158596,25.072539,33.599952,36.66,161.293547,159.988743,...,0.885024,0.006705,0.000000,0.006705,0.003252,0.003453,0.000000,0.000000,0.000000,0.0
2022-12-31 22:00:00+00:00,0.00,0.0,0.00000,NaN,0.000000,NaN,NaN,0.00,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-31 23:00:00+00:00,0.00,0.0,0.00000,NaN,0.000000,NaN,NaN,0.00,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# If resulting file is too big, resave data compressed
df.to_hdf(file_path, key="simulation_data", format="table", complib="zlib", complevel=9, mode="w")
logger.info(f"File saved to {file_path}")

2025-04-01 18:45:26.798 | INFO     | __main__:<module>:2 - File saved to /workspaces/SOLhycool/simulation/results/20220101_20221231/cc_static/df_sim_eval_at_20250401T0935_andasol.h5

In [10]:
# Exportar datos a csv para que se puedan importar en otros entornos
df.to_csv(file_path.with_suffix(".csv"))

In [23]:
# Resample results monthly
df = df.resample("SME").mean()
df

,Tamb,HR,mv,Tv,qc,Tc_in,Tc_out,Tcond,Qc_released,Qc_absorbed,...,Vavail_s1,Je,Jw,J,Je_c,Je_dc,Je_wct,Jw_wct,Jw_s1,Jw_s2
2021-12-31 00:00:00+00:00,2.082798,12.107887,49.653919,35.472568,3.503704,24.947462,33.482845,7.812411,33.313071,32.881082,...,0.885024,0.407286,0.004399,0.411686,0.339196,0.004113,0.063977,0.004399,0.004399,0.000000
2022-01-15 00:00:00+00:00,1.510469,7.958333,41.159601,38.690508,2.137705,25.117451,36.557467,5.944635,27.531205,27.185617,...,0.885024,0.363251,0.005434,0.368685,0.283111,0.004645,0.075496,0.005434,0.005434,0.000000
2022-01-31 00:00:00+00:00,1.683722,8.913889,41.258484,35.964687,2.834465,24.971100,33.956273,6.393722,27.660379,27.312885,...,0.885024,0.452133,0.004508,0.456641,0.373791,0.006568,0.071774,0.004508,0.004508,0.000000
2022-02-15 00:00:00+00:00,3.518654,14.423077,80.230906,38.122188,4.319929,24.916285,36.183809,11.729904,53.666584,53.158754,...,0.885024,0.337218,0.005378,0.342596,0.257749,0.002379,0.077090,0.005378,0.005378,0.000000
2022-02-28 00:00:00+00:00,3.482500,17.785417,87.385975,38.064959,4.875403,24.949494,36.097270,12.794056,58.455064,57.963962,...,0.850242,0.708039,0.005294,0.713334,0.552556,0.009840,0.145643,0.005294,0.005294,0.000000
2022-03-15 00:00:00+00:00,4.594271,14.476562,85.292433,38.372581,4.566519,24.930228,36.407582,12.391146,57.034902,56.460852,...,0.850242,0.467551,0.005611,0.473162,0.341810,0.012206,0.113535,0.005611,0.005611,0.000000
2022-03-31 00:00:00+00:00,7.968111,28.873611,151.702088,39.381371,7.299529,25.082327,37.280667,21.550361,101.391664,99.962419,...,0.900483,0.327468,0.005943,0.333411,0.237945,0.001434,0.088090,0.005943,0.005943,0.000000
2022-04-15 00:00:00+00:00,5.159000,22.838194,114.608710,39.360268,5.611266,25.099910,37.254304,16.290778,76.604202,75.673020,...,0.900483,0.277471,0.005695,0.283166,0.212913,0.001585,0.062973,0.005695,0.005695,0.000000
2022-04-30 00:00:00+00:00,9.099000,26.136111,177.420729,40.382682,7.821998,25.147462,38.218069,24.678306,118.512692,117.189198,...,0.724638,0.272868,0.006387,0.279255,0.192028,0.000912,0.079929,0.006387,0.006387,0.000000
2022-05-15 00:00:00+00:00,10.262656,23.208333,148.013991,40.243604,6.623870,25.221537,37.989358,20.645807,98.876422,97.021313,...,0.724638,0.283844,0.006586,0.290430,0.180346,0.002232,0.101266,0.006586,0.006586,0.000000
2022-05-31 00:00:00+00:00,15.100000,28.413889,209.170471,40.080646,9.497872,25.195497,37.881648,29.281139,139.752892,137.536863,...,0.519807,0.318031,0.006715,0.324746,0.206110,0.000307,0.111614,0.006715,0.006715,0.000000
2022-06-15 00:00:00+00:00,15.700000,22.266667,181.864183,40.234978,8.156049,25.201816,38.010753,25.370389,121.487006,119.267027,...,0.519807,0.257426,0.007160,0.264587,0.150019,0.004448,0.102959,0.007160,0.007160,0.000000
2022-06-30 00:00:00+00:00,18.758611,22.011111,211.424731,40.481111,10.031656,25.762198,37.758121,29.348806,141.217993,137.711446,...,0.110145,0.351064,0.278000,0.629064,0.178891,0.065476,0.106697,0.278000,0.003170,0.274830
2022-07-15 00:00:00+00:00,18.247656,19.898438,194.862067,40.356240,9.217948,25.647595,37.674304,27.114349,130.158313,126.724353,...,0.110145,0.334598,0.316394,0.650993,0.167728,0.049605,0.117265,0.316394,0.003167,0.313228
2022-07-31 00:00:00+00:00,16.145833,20.772222,182.796734,40.059826,8.661374,25.511093,37.516679,25.593778,122.123770,118.792597,...,0.000000,0.358649,0.504661,0.863310,0.165656,0.079818,0.113175,0.504661,0.000000,0.504661
2022-08-15 00:00:00+00:00,17.260677,19.901042,176.924990,40.197373,8.466359,25.666660,37.628734,24.704635,118.196844,115.197512,...,0.000000,0.402464,0.693831,1.096295,0.196543,0.059559,0.146363,0.693831,0.000000,0.693831
2022-08-31 00:00:00+00:00,11.775833,18.594444,136.743334,40.326353,6.480452,25.671571,37.665455,19.043000,91.345634,88.640035,...,0.019324,0.391064,0.469076,0.860140,0.182058,0.088448,0.120558,0.469076,0.000551,0.468525
2022-09-15 00:00:00+00:00,8.776667,18.855556,119.389927,39.123376,6.098689,25.356499,36.700095,17.062139,79.816497,77.282726,...,0.019324,0.343964,0.194999,0.538964,0.169843,0.095642,0.078479,0.194999,0.000543,0.194457
2022-09-30 00:00:00+00:00,6.008333,14.258333,84.979148,39.261261,4.120016,25.118217,37.115866,12.105556,56.803945,55.780574,...,0.504348,0.273180,0.006133,0.279314,0.178562,0.009137,0.085481,0.006133,0.006133,0.000000
2022-10-15 00:00:00+00:00,5.148438,16.044271,80.770852,37.800909,4.420566,24.963266,35.801485,11.911224,54.055011,53.315325,...,0.504348,0.213174,0.005339,0.218512,0.151296,0.010127,0.051751,0.005339,0.005339,0.000000
2022-10-31 00:00:00+00:00,2.749278,12.513889,48.553802,35.125190,3.531116,24.775037,33.301008,7.708028,32.568984,32.214294,...,0.861836,0.343779,0.004311,0.348091,0.271135,0.016074,0.056570,0.004311,0.004311,0.000000
2022-11-15 00:00:00+00:00,2.316944,11.933333,48.378499,35.977067,3.242890,24.938339,34.014281,7.495222,32.434998,32.009324,...,0.861836,0.283984,0.004616,0.288600,0.231127,0.006746,0.046111,0.004616,0.004616,0.000000
2022-11-30 00:00:00+00:00,1.182056,8.861111,28.444919,35.256304,2.086883,24.985656,33.215080,4.504972,19.088110,18.799616,...,1.200000,0.331675,0.004518,0.336193,0.278677,0.006966,0.046032,0.004518,0.004518,0.000000
2022-12-15 00:00:00+00:00,1.822552,12.404297,37.296486,33.218356,3.425349,24.754604,31.417559,6.314948,25.074203,24.743283,...,1.200000,0.238001,0.003671,0.241673,0.199899,0.003492,0.034610,0.003671,0.003671,0.000000
2022-12-31 00:00:00+00:00,2.304167,17.166667,49.751608,33.461667,4.842552,25.083292,31.162276,8.365417,33.458526,32.983160,...,0.885024,0.034770,0.002189,0.036959,0.029589,0.003612,0.001569,0.002189,0.002189,0.000000

In [24]:
plot_config = hjson.load(open(data_path / "plot_config_year.hjson"))
plot_config["subtitle"] = f"Evaluation results for {results_path.parts[-2].replace('_', ' ')}"

# Move contents of load conditions to cooling power and remove it
plot_config["plots"]["cooling_power_distribution"]["ylims_left"] = [0,250]
plot_config["plots"]["cooling_power_distribution"]["traces_right"] = plot_config["plots"]["load_conditions"]["traces_right"]
plot_config["plots"]["cooling_power_distribution"].update({param_id: plot_config["plots"]["load_conditions"][param_id] for param_id in ["ylabels_right", "ylims_right"]})
plot_config["plots"].pop("load_conditions")

fig = experimental_results_plot(
    plot_config, 
    df=df, # best_dfs[0],  
    resample=False,
)
# fig.update_layout(width=1000, height=1000)

fig

In [131]:
save_figure(
    fig,
    figure_name=file_path.stem,
    # figure_name=f"{df.index[0]:%Y%m%d}_{df.index[1]:%Y%m%d}_optim_viz",
    # figure_path=Path("../results"),
    figure_path=file_path.parent,
    formats=["png", "html"],
)

2025-04-01 16:26:15.431 | INFO     | phd_visualizations:save_figure:38 - Figure saved in [PosixPath('/workspaces/SOLhycool/simulation/results/20220101_20221231/cc_static')]/df_sim_eval_at_20250401T0935_andasol.png
2025-04-01 16:26:15.436 | INFO     | phd_visualizations:save_figure:38 - Figure saved in [PosixPath('/workspaces/SOLhycool/simulation/results/20220101_20221231/cc_static')]/df_sim_eval_at_20250401T0935_andasol.html
2025-04-01 16:26:15.436 | INFO     | phd_visualizations:save_figure:38 - Figure saved in [PosixPath('/workspaces/SOLhycool/simulation/results/20220101_20221231/cc_static')]/df_sim_eval_at_20250401T0935_andasol.html

# Yearly analytics

In [115]:
df_year = df.copy()
df_year.drop("Qc_transfered", inplace=True, axis=1)
indexer = df_year["Qc_released"] > 0
df_year = df_year[indexer].mean()
# df_year

In [116]:
fig = year_pie_plot(df_year, )
fig

In [117]:
save_figure(
    fig,
    figure_name=f"year_analysis_{file_path.stem}",
    # figure_name=f"{df.index[0]:%Y%m%d}_{df.index[1]:%Y%m%d}_optim_viz",
    # figure_path=Path("../results"),
    figure_path=file_path.parent,
    formats=["png", "html", "svg"],
)

2025-04-01 16:21:44.757 | INFO     | phd_visualizations:save_figure:38 - Figure saved in [PosixPath('/workspaces/SOLhycool/simulation/results/20220101_20221231/cc_static')]/year_analysis_df_sim_eval_at_20250401T0935_andasol.png
2025-04-01 16:21:44.759 | INFO     | phd_visualizations:save_figure:38 - Figure saved in [PosixPath('/workspaces/SOLhycool/simulation/results/20220101_20221231/cc_static')]/year_analysis_df_sim_eval_at_20250401T0935_andasol.html
2025-04-01 16:21:44.759 | INFO     | phd_visualizations:save_figure:38 - Figure saved in [PosixPath('/workspaces/SOLhycool/simulation/results/20220101_20221231/cc_static')]/year_analysis_df_sim_eval_at_20250401T0935_andasol.html
2025-04-01 16:21:44.970 | INFO     | phd_visualizations:save_figure:38 - Figure saved in [PosixPath('/workspaces/SOLhycool/simulation/results/20220101_20221231/cc_static')]/year_analysis_df_sim_eval_at_20250401T0935_andasol.svg